### ISSUE TITLE
The clock example in "Live Demo" has the hands slowly drifting off of the screen

### ISSUE THREAD

**Issue by jasikpark** [utkarshkukreti/draco#5]
<img width="590" alt="screenshot 2018-10-28 18 56 51" src="https://user-images.githubusercontent.com/10626596/47623794-4d0e1500-dae3-11e8-9ce3-fc1feedb25bd.png">

**Comment by utkarshkukreti** [comment]
Let me know if it's fixed now in whichever browser / OS combination you were testing on!
